version: '3.9'

services:
  backend-config:
    container_name: backend-config
    image: backend-config
    build: .
    restart: always
    ports:
      - "80:80"
    depends_on:
      - postgres-config
    networks:
      - parking

  postgres-config:
    container_name: postgres-config
    image: postgres:15-alpine
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - ./data/master:/var/lib/postgresql/data
    restart: always
    networks:
      - parking
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5435:5432"

networks:
  parking:
    external: true